services:
  nicknamer2:
    image: nicknamer2
    container_name: nicknamer
    build: .
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /app/data

#volumes:
#  nicknamer2db:
