apiVersion: v1
kind: Pod
metadata:
  name: nicknamer2
spec:
  containers:
    - image: smallketchup/nicknamer2
      name: nicknamer2
      imagePullPolicy: Never
      volumeMounts:
      - name: nicknamer2db
        mountPath: /app/data
  volumes:
    - name: nicknamer2db
      emptyDir: {}
